name: Deploy to Railway

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run basic tests
      run: |
        python -c "
        import sys
        sys.path.append('.')
        try:
            from app import app
            from routes import *
            print('✓ Application imports successfully')
            
            # Test basic route availability
            with app.test_client() as client:
                response = client.get('/')
                print(f'✓ Home route responds with status: {response.status_code}')
            
            print('✓ All basic tests passed')
        except Exception as e:
            print(f'✗ Test failed: {e}')
            sys.exit(1)
        "
        
    - name: Deploy to Railway
      uses: railwayapp/railway-deploy-action@v1.1.0
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: ${{ secrets.RAILWAY_SERVICE }}
        
    - name: Post-deploy verification
      run: |
        echo "✓ Deployment initiated successfully"
        echo "✓ Railway will handle the build and deployment process"
        echo "✓ Check Railway dashboard for deployment status"